### ISSUE TITLE
error when running code

### ISSUE THREAD

**Issue by karimmahalian** [Ashraf-Kamal/Hate_Speech_Detection#1]
Hi,

First thank u for sharing ir code with us. I ve tried to run it on my own dataset but I got this error 

ValueError: Cannot do batch_dot on inputs with shapes (None, 5, 5, 4) and (None, 5, 63, 4) with axes=[2, 3]. x.shape[2] != y.shape[3] (5 != 4).

In this line

capsule = Capsule(num_capsule=Num_capsule, dim_capsule=Dim_capsule, routings=Routings, share_weights=True)(BiGRU)

Thanks in advance

**Comment by Ashraf-Kamal** [comment]
The versions of Tensorflow and keras should be 1.15 and 2.2.4, respectively.

Below is the pre-requisite:


    Twitter REST API
    Keras 2.2.4
    Numpy
    Pandas
    Python 3.7
    GloVe
    Tensorflow 1.15

**Comment by Ashraf-Kamal** [comment]
The versions of Tensorflow and keras should be 1.15 and 2.2.4, respectively.

Below is the pre-requisite:

Twitter REST API
Keras 2.2.4
Numpy
Pandas
Python 3.7
GloVe
Tensorflow 1.15
